# Generated by Django 4.2.13 on 2024-06-25 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiFront', '0003_worktype'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('block_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floors', to='apiFront.blocksection')),
            ],
        ),
        migrations.AddField(
            model_name='blocksection',
            name='object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='block_sections', to='apiFront.object'),
        ),
    ]
