# Generated by Django 4.2.13 on 2024-06-25 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiFront', '0004_blocksection_object_floor_blocksection_object'),
    ]

    operations = [
        migrations.AddField(
            model_name='floor',
            name='object',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Объект', to='apiFront.object'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='floor',
            name='block_section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Этажи', to='apiFront.blocksection'),
        ),
    ]
