# Generated by Django 4.2.13 on 2024-06-25 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiFront', '0005_floor_object_alter_floor_block_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='blocksection',
            name='number_of_floors',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Floor',
        ),
    ]
