# Generated by Django 4.2.13 on 2024-06-25 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiFront', '0006_blocksection_number_of_floors_delete_floor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blocksection',
            options={'verbose_name': 'Блок/Секция', 'verbose_name_plural': 'Блоки/Секции'},
        ),
        migrations.AlterModelOptions(
            name='object',
            options={'verbose_name': 'Объект', 'verbose_name_plural': 'Объекты'},
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'verbose_name': 'Организация', 'verbose_name_plural': 'Организации'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterModelOptions(
            name='worktype',
            options={'verbose_name': 'Вид работ', 'verbose_name_plural': 'Виды работ'},
        ),
        migrations.AlterField(
            model_name='blocksection',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Блок/Секция'),
        ),
        migrations.AlterField(
            model_name='blocksection',
            name='number_of_floors',
            field=models.IntegerField(verbose_name='Количество этажей'),
        ),
        migrations.AlterField(
            model_name='blocksection',
            name='object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='block_sections', to='apiFront.object', verbose_name='Объект'),
        ),
        migrations.AlterField(
            model_name='object',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Название объекта'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='is_general_contractor',
            field=models.BooleanField(default=False, verbose_name='Генеральный подрядчик'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='organization',
            field=models.CharField(max_length=255, verbose_name='Организация'),
        ),
        migrations.AlterField(
            model_name='user',
            name='chat_id',
            field=models.CharField(max_length=100, unique=True, verbose_name='Chat ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(max_length=255, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_authorized',
            field=models.BooleanField(default=False, verbose_name='Авторизован'),
        ),
        migrations.AlterField(
            model_name='user',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiFront.organization', verbose_name='Организация'),
        ),
        migrations.AlterField(
            model_name='worktype',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Вид работ'),
        ),
        migrations.CreateModel(
            name='FrontTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor', models.IntegerField(verbose_name='Этаж')),
                ('status', models.CharField(choices=[('transferred', 'Передано'), ('approved', 'Одобрено'), ('with_remarks', 'Есть замечания')], max_length=20, verbose_name='Статус')),
                ('photos', models.JSONField(default=list, verbose_name='Фотографии')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Замечания')),
                ('block_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiFront.blocksection', verbose_name='Блок/Секция')),
                ('boss', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boss_transfers', to='apiFront.user', verbose_name='Генеральный подрядчик')),
                ('next_work_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_transfers', to='apiFront.worktype', verbose_name='Следующий вид работы')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiFront.object', verbose_name='Объект')),
                ('receiver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_transfers', to='apiFront.user', verbose_name='Получатель')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_transfers', to='apiFront.user', verbose_name='Отправитель')),
                ('work_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiFront.worktype', verbose_name='Вид работы')),
            ],
            options={
                'verbose_name': 'Передача фронта',
                'verbose_name_plural': 'Передачи фронта',
            },
        ),
    ]
