# Generated by Django 4.2.13 on 2024-06-25 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiFront', '0007_alter_blocksection_options_alter_object_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fronttransfer',
            name='sender',
            field=models.CharField(max_length=100, verbose_name='Chat ID отправителя'),
        ),
    ]
