# Generated by Django 4.2.13 on 2024-06-25 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiFront', '0010_remove_fronttransfer_photos_fronttransfer_photo1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fronttransfer',
            name='floor',
            field=models.CharField(max_length=200, verbose_name='Этаж'),
        ),
    ]
