# Generated by Django 4.2.13 on 2024-06-29 15:06

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('apiFront', '0014_alter_fronttransfer_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='fronttransfer',
            name='photo_ids',
            field=jsonfield.fields.JSONField(default=list, verbose_name='ID фотографий'),
        ),
    ]
