# Generated by Django 4.2.13 on 2024-07-01 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiFront', '0016_alter_fronttransfer_photo_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fronttransfer',
            name='status',
            field=models.CharField(choices=[('transferred', 'Передано'), ('approved', 'Одобрено'), ('with_remarks', 'Есть замечания'), ('on_consideration', 'На рассмотрении'), ('deleted', 'Удалено из-за ошибки'), ('in_process', 'В процессе выполнения')], max_length=20, verbose_name='Статус'),
        ),
    ]
