# Generated by Django 4.2.13 on 2024-07-01 13:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('apiFront', '0017_alter_fronttransfer_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='fronttransfer',
            name='approval_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата принятия'),
        ),
        migrations.AlterField(
            model_name='fronttransfer',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата передачи'),
        ),
    ]
