# Generated by Django 4.2.13 on 2024-07-01 13:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('apiFront', '0018_fronttransfer_approval_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fronttransfer',
            name='approval_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Дата принятия'),
        ),
    ]
